version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn --frozen-lockfile
      - run:
          name: Run yests
          command: |
            yarn test
  pack: 
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn --frozen-lockfile
      - run:
          name: compiles
          command: |
            yarn build

workflows: 
  build-and-packge:
    jobs:
      - build
      - pack:
          requires:
            - build